# Generated by Django 5.2.3 on 2025-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=250, verbose_name='Duyuru Başlığı')),
                ('icerik', models.TextField(verbose_name='Duyuru İçeriği')),
                ('yayin_tarihi', models.DateField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('resim_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim URL')),
                ('kaynak_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kaynak URL')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'ordering': ['-yayin_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=250, verbose_name='Haber Başlığı')),
                ('icerik', models.TextField(verbose_name='Haber İçeriği')),
                ('yayin_tarihi', models.DateField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('resim_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Resim URL')),
                ('kaynak_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Kaynak URL')),
            ],
            options={
                'verbose_name': 'Haber',
                'ordering': ['-yayin_tarihi'],
            },
        ),
    ]
