# Generated by Django 5.2.3 on 2025-07-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duyuru',
            name='resim_url',
        ),
        migrations.AddField(
            model_name='duyuru',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='duyuru_resim/', verbose_name='Resim URL'),
        ),
    ]
