# Generated by Django 5.2.3 on 2025-07-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0003_remove_duyuru_resim_url_duyuru_resim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duyuru',
            old_name='resim',
            new_name='resim_url',
        ),
    ]
