# Generated by Django 5.2.3 on 2025-07-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0004_rename_resim_duyuru_resim_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haber',
            name='resim_url',
        ),
    ]
